
import type { Member } from './types';

// These placeholders are now generated by the server-side `getGenderPlaceholder` function.
// This ensures consistency and simplifies client-side code.
const malePlaceholder = 'https://placehold.co/100x100.png';
const femalePlaceholder = 'https://placehold.co/100x100.png';


export const members: Member[] = [
  {
    id: '1',
    name: 'Eleanor Vance',
    photoUrl: femalePlaceholder,
    dateOfBirth: '1945-03-12',
    dateOfDeath: null,
    relationship: 'Matriarch',
    gender: 'Female',
    parents: [],
    bloodType: 'O+',
    mobile: '123-456-7890',
    email: 'eleanor@vance.com',
    birthPlace: 'New York, USA',
    occupation: 'Homemaker'
  },
  {
    id: '2',
    name: 'Arthur Vance',
    photoUrl: malePlaceholder,
    dateOfBirth: '1943-07-21',
    dateOfDeath: '2015-01-10',
    relationship: 'Patriarch',
    gender: 'Male',
    parents: [],
    bloodType: 'A-',
    mobile: '123-456-7891',
    email: 'arthur@vance.com',
    birthPlace: 'Boston, USA',
    occupation: 'Businessman'
  },
  {
    id: '3',
    name: 'James Vance',
    photoUrl: malePlaceholder,
    dateOfBirth: '1968-05-18',
    dateOfDeath: null,
    relationship: 'Son',
    gender: 'Male',
    parents: ['1', '2'],
    bloodType: 'A+',
    mobile: '234-567-8901',
    email: 'james@vance.com',
    birthPlace: 'New York, USA',
    occupation: 'Lawyer'
  },
  {
    id: '4',
    name: 'Clara (Vance) Chen',
    photoUrl: femalePlaceholder,
    dateOfBirth: '1970-11-30',
    dateOfDeath: null,
    relationship: 'Daughter',
    gender: 'Female',
    parents: ['1', '2'],
    bloodType: 'B+',
    mobile: '345-678-9012',
    email: 'clara@chen.com',
    birthPlace: 'New York, USA',
    occupation: 'Doctor'
  },
  {
    id: '5',
    name: 'Sofia Chen',
    photoUrl: femalePlaceholder,
    dateOfBirth: '1995-09-02',
    dateOfDeath: null,
    relationship: 'Granddaughter',
    gender: 'Female',
    parents: ['4', '8'],
    bloodType: 'B+',
    mobile: '456-789-0123',
    email: 'sofia@chen.com',
    birthPlace: 'Chicago, USA',
    occupation: 'Student'
  },
  {
    id: '6',
    name: 'Leo Vance',
    photoUrl: malePlaceholder,
    dateOfBirth: '1998-02-14',
    dateOfDeath: null,
    relationship: 'Grandson',
    gender: 'Male',
    parents: ['3', '7'],
    bloodType: 'A+',
    mobile: '567-890-1234',
    email: 'leo@vance.com',
    birthPlace: 'Los Angeles, USA',
    occupation: 'Artist'
  },
   {
    id: '7',
    name: 'Isabella Rossi',
    photoUrl: femalePlaceholder,
    dateOfBirth: '1972-01-25',
    dateOfDeath: null,
    relationship: 'Daughter-in-law',
    gender: 'Female',
    parents: [],
    bloodType: 'AB+',
    mobile: '678-901-2345',
    email: 'isabella@vance.com',
    birthPlace: 'Rome, Italy',
    occupation: 'Chef'
  },
  {
    id: '8',
    name: 'David Chen',
    photoUrl: malePlaceholder,
    dateOfBirth: '1969-08-15',
    dateOfDeath: null,
    relationship: 'Son-in-law',
    gender: 'Male',
    parents: [],
    bloodType: 'O-',
    mobile: '789-012-3456',
    email: 'david@chen.com',
    birthPlace: 'Beijing, China',
    occupation: 'Engineer'
  },
  {
    id: 'wPcpsvI8jcBD7smOjWVN',
    name: 'Kutty Maamu',
    photoUrl: 'https://storage.googleapis.com/kith-and-kin-43tyu.appspot.com/profile_pictures/wPcpsvI8jcBD7smOjWVN.jpg',
    gender: 'Male',
    parents: [],
    spouseName: '',
    otherParentName: '',
    bloodType: '',
    dateOfBirth: '1895-03-19',
    dateOfDeath: null,
    mobile: '',
    email: '',
    birthPlace: 'Kerala, India',
    occupation: '',
    relationship: 'Great-Grandfather',
  }
];
